begin;
create function pg_temp.ok(value boolean,label text) returns void language plpgsql as $$begin if value is distinct from true then raise exception 'FAILED: %',label;end if;end$$;
create temp table mode_fixture(v jsonb);
insert into mode_fixture values ('{"schemaVersion":1,"mode":"split","question":1,"taskEpoch":"10000000-0000-4000-8000-000000000050","groups":[{"id":"10000000-0000-4000-8000-000000000001","label":"Segitiga Biru","attendanceNumbers":[1,2]},{"id":"10000000-0000-4000-8000-000000000002","label":"Lingkaran Oranye","attendanceNumbers":[3,4]}],"split":{"panels":[]}}');
update mode_fixture set v=jsonb_set(v,'{split,panels}',(select jsonb_agg(jsonb_build_object('groupId',g->'id','exercises','[{"id":"10000000-0000-4000-8000-000000000101","prompt":[{"kind":"text","text":"Bandingkan model."}],"tool":{"kind":"ratio","baseX":2,"baseY":3,"targetX":6}},{"id":"10000000-0000-4000-8000-000000000102","prompt":[{"kind":"text","text":"Jelaskan caramu."}],"tool":{"kind":"ratio","baseX":2,"baseY":3,"targetX":8}}]'::jsonb)) from jsonb_array_elements(v->'groups') g));
select pg_temp.ok(pn_private.valid_public_state(v),'two panel projection') from mode_fixture;
select pg_temp.ok(not pn_private.valid_public_state(jsonb_set(v,'{split,panels}',jsonb_build_array(v#>'{split,panels,0}'))),'one panel rejected') from mode_fixture;
select pg_temp.ok(not pn_private.valid_public_state(jsonb_set(v,'{split,panels,1,groupId}','"10000000-0000-4000-8000-000000000099"')),'unknown group rejected') from mode_fixture;
select pg_temp.ok(not pn_private.valid_public_state(jsonb_set(v,'{split,panels,1,groupId}',v#>'{split,panels,0,groupId}')),'duplicate group rejected') from mode_fixture;
select pg_temp.ok(not pn_private.valid_public_state(jsonb_set(v,'{split,panels,0,exercises,1,id}',v#>'{split,panels,0,exercises,0,id}')),'duplicate exercise rejected') from mode_fixture;
select pg_temp.ok(not pn_private.valid_public_state(jsonb_set(v,'{split,panels,0,name}','"CANARY"')),'panel identity rejected') from mode_fixture;
select pg_temp.ok(not pn_private.valid_public_state(jsonb_set(v,'{split,panels,0,exercises,0,answerKey}','"B"')),'nested key rejected') from mode_fixture;
select pg_temp.ok(not pn_private.valid_public_state(jsonb_set(v,'{split,panels,0,exercises,0,tool,stepId}','"D3"')),'tool level rejected') from mode_fixture;
select pg_temp.ok(not pn_private.valid_public_state(v||'{"mode":"station"}'),'split is mode bound') from mode_fixture;
select pg_temp.ok(not pn_private.valid_public_state(v-'split'),'split requires panels') from mode_fixture;
select pg_temp.ok(pn_private.valid_public_state(v||'{"layout":{"touchZone":"sd","largeObjects":true}}'),'layout settings valid') from mode_fixture;
select pg_temp.ok(not pn_private.valid_public_state(v||'{"layout":{"touchZone":"sd","largeObjects":true,"name":"CANARY"}}'),'layout strict') from mode_fixture;
update mode_fixture set v=v||jsonb_build_object('mode','spotlight','viewId',v->'taskEpoch','spotlight',jsonb_build_object('id','10000000-0000-4000-8000-000000000060','returnMode','split','tool',v#>'{split,panels,0,exercises,0,tool}'));
select pg_temp.ok(pn_private.valid_public_state(v),'spotlight retains valid split descriptors') from mode_fixture;
select pg_temp.ok(pn_private.valid_public_state(jsonb_set(v,'{spotlight,groupId}',v#>'{groups,1,id}')),'selected spotlight group allowed') from mode_fixture;
select pg_temp.ok(not pn_private.valid_public_state(jsonb_set(v,'{spotlight,groupId}','"10000000-0000-4000-8000-000000000099"')),'unknown spotlight group rejected') from mode_fixture;
select pg_temp.ok(not pn_private.valid_public_state(v-'viewId'),'resume view identity required') from mode_fixture;
select pg_temp.ok(not pn_private.valid_public_state(jsonb_set(v,'{spotlight,returnMode}','"spotlight"')),'no recursive spotlight') from mode_fixture;
select pg_temp.ok(not pn_private.valid_public_state(jsonb_set(v,'{spotlight,returnMode}','"reflection"')),'no ink retention in spotlight') from mode_fixture;
select pg_temp.ok(not pn_private.valid_public_state(jsonb_set(v,'{spotlight,tool,history}','[]')),'no local model history') from mode_fixture;
select pg_temp.ok(pn_private.valid_public_state((v-'split'-'spotlight')||jsonb_build_object('mode','together','tool',v#>'{spotlight,tool}')),'together public model task') from mode_fixture;
select pg_temp.ok(not pn_private.valid_public_state((v-'split'-'spotlight')||'{"mode":"together"}'),'together needs model') from mode_fixture;
select pg_temp.ok(not has_function_privilege('authenticated','pn_private.valid_public_split(jsonb,jsonb)','EXECUTE'),'helper private');
select 'PASS 22 board mode SQL guards';
rollback;
