begin;
create temp table assertions(label text);
grant select,insert on assertions to authenticated;
create function pg_temp.ok(v boolean,label text) returns void language plpgsql as $$begin if v is distinct from true then raise exception 'FAILED: %',label;end if;insert into assertions values(label);end$$;
create temp table sync_input(data jsonb);
insert into sync_input values(__SYNC_MUTATION__::jsonb);
grant select,update on sync_input to authenticated;
insert into auth.users(id,email,is_anonymous) values('10000000-0000-4000-8000-000000000001','history-a@qa.invalid',false);
insert into public.classes(id,owner_id,label,grade,student_count,runtime_mode) select (data->>'classId')::uuid,'10000000-0000-4000-8000-000000000001','7T',7,3,'demo' from sync_input;
insert into public.students(id,class_id,owner_id,attendance_number) select (r->>'id')::uuid,(data->>'classId')::uuid,'10000000-0000-4000-8000-000000000001',(r->>'attendanceNumber')::int from sync_input,jsonb_array_elements(data->'payload'->'roster') r;
select pg_temp.ok(not has_function_privilege('authenticated','public.sync_action_v2(text,jsonb)','EXECUTE'),'old writer RPC cannot bypass history validation');
set local role authenticated;
set local request.jwt.claims='{"sub":"10000000-0000-4000-8000-000000000001","is_anonymous":false}';
select pg_temp.ok((select public.sync_action('apply',jsonb_set(data,'{payload,oral,0,studentId}','"30000000-0000-4000-8000-000000000088"'))->>'error'='FORBIDDEN' from sync_input),'oral cross-student link forbidden');
select pg_temp.ok((select public.sync_action('apply',jsonb_set(data,'{payload,turns,0,events,0,pilots,0}','"30000000-0000-4000-8000-000000000088"'))->>'error'='FORBIDDEN' from sync_input),'turn cross-student link forbidden');
select pg_temp.ok((select public.sync_action('apply',jsonb_set(data,'{payload,oral,0,baseline}','{}'))->>'error'='INVALID_INPUT' from sync_input),'client mastery checkpoint rejected');
select pg_temp.ok((select public.sync_action('apply',data)->>'status'='accepted' from sync_input),'oral and role evidence accepted');
select pg_temp.ok((select public.sync_action('apply',data)->>'revision'='1' from sync_input),'history retry remains same revision');
update sync_input set data=data||'{"eventId":"30000000-0000-4000-8000-000000000055","baseRevision":1,"clientSequence":2}';
select pg_temp.ok((select public.sync_action('apply',jsonb_set(data,'{payload,oral}','[]'))->>'error'='CONFLICT' from sync_input),'oral history cannot silently disappear');
select pg_temp.ok((select public.sync_action('apply',jsonb_set(data,'{payload,turns}','[]'))->>'error'='CONFLICT' from sync_input),'counted role event immutable');
select pg_temp.ok((select public.sync_action('apply',jsonb_set(data,'{payload,oral,0,answers,0,result}','"silent"'))->>'error'='CONFLICT' from sync_input),'same oral revision altered result rejected');
reset role;
select 'PASS '||count(*)||' history SQL assertions' from assertions;
select 'ok - '||label from assertions;
rollback;
