begin;
create function pg_temp.ok(value boolean,label text) returns void language plpgsql as $$begin if value is distinct from true then raise exception 'FAILED: %',label;end if;end$$;
create temp table tool_fixture(v jsonb);
insert into tool_fixture values('{"kind":"fractions","operation":"add","left":{"numerator":1,"denominator":2},"right":{"numerator":1,"denominator":3}}');
select pg_temp.ok(pn_private.valid_public_tool(v),'fraction tool accepted') from tool_fixture;
select pg_temp.ok(not pn_private.valid_public_tool(v||'{"answerKey":"A"}'),'answer key rejected') from tool_fixture;
select pg_temp.ok(not pn_private.valid_public_tool(v||'{"name":"CANARY"}'),'identity rejected') from tool_fixture;
select pg_temp.ok(not pn_private.valid_public_tool(jsonb_set(v,'{left,stepId}','"D2"')),'nested level rejected') from tool_fixture;
select pg_temp.ok(not pn_private.valid_public_tool(jsonb_set(v,'{left,denominator}','0')),'zero denominator rejected') from tool_fixture;
select pg_temp.ok(not pn_private.valid_public_tool(jsonb_set(v,'{left,denominator}','5')),'LCM greater than 12 rejected') from tool_fixture;
select pg_temp.ok(not pn_private.valid_public_tool(jsonb_set(v,'{left,numerator}','3')),'operand larger than whole rejected') from tool_fixture;
select pg_temp.ok(not pn_private.valid_public_tool(jsonb_set(v,'{operation}','null')),'null operation rejected') from tool_fixture;
select pg_temp.ok(pn_private.valid_public_tool('{"kind":"ratio","baseX":2,"baseY":3,"targetX":6}'),'ratio accepted');
select pg_temp.ok(not pn_private.valid_public_tool('{"kind":"ratio","baseX":0,"baseY":3,"targetX":6}'),'zero ratio rejected');
select pg_temp.ok(not pn_private.valid_public_tool('{"kind":"ratio","baseX":2,"baseY":3,"targetX":6,"name":"CANARY"}'),'ratio name rejected');
select pg_temp.ok(pn_private.valid_public_tool('{"kind":"algebra","groups":3,"xPerGroup":1,"constantPerGroup":-4}'),'signed algebra accepted');
select pg_temp.ok(not pn_private.valid_public_tool('{"kind":"algebra","groups":7,"xPerGroup":1,"constantPerGroup":4}'),'group overflow rejected');
select pg_temp.ok(not pn_private.valid_public_tool('{"kind":"algebra","groups":3,"xPerGroup":1,"constantPerGroup":4,"answerKey":"A"}'),'algebra key rejected');
select pg_temp.ok(pn_private.valid_public_tool('{"kind":"number-line","origin":{"numerator":-3,"denominator":1},"delta":{"numerator":-5,"denominator":1},"orientation":"horizontal"}'),'number line accepted');
select pg_temp.ok(not pn_private.valid_public_tool('{"kind":"number-line","origin":{"numerator":-3,"denominator":1,"name":"CANARY"},"delta":{"numerator":-5,"denominator":1},"orientation":"horizontal"}'),'nested identity rejected');
select pg_temp.ok(not pn_private.valid_public_tool('{"kind":"number-line","origin":{"numerator":-3,"denominator":1},"delta":{"numerator":-5,"denominator":0},"orientation":"horizontal"}'),'line denominator zero rejected');
select pg_temp.ok(not pn_private.valid_public_tool('{"kind":"fractions","operation":"equivalent","left":{"numerator":1,"denominator":7},"right":{"numerator":1,"denominator":2}}'),'unrenderable equivalent rejected');
select pg_temp.ok(pn_private.valid_public_state('{"schemaVersion":1,"mode":"station","question":1,"taskEpoch":"10000000-0000-4000-8000-000000000001","groups":[],"pattern":"predict","tool":{"kind":"ratio","baseX":2,"baseY":3,"targetX":6}}'),'pattern accepted');
select pg_temp.ok(not pn_private.valid_public_state('{"schemaVersion":1,"mode":"station","question":1,"taskEpoch":"10000000-0000-4000-8000-000000000001","groups":[],"pattern":"predict"}'),'pattern requires tool');
select pg_temp.ok(not pn_private.valid_public_state('{"schemaVersion":1,"mode":"station","question":1,"taskEpoch":"10000000-0000-4000-8000-000000000001","groups":[],"pattern":{"name":"CANARY"},"tool":{"kind":"ratio","baseX":2,"baseY":3,"targetX":6}}'),'pattern object rejected');
select pg_temp.ok((select pg_get_expr(conbin,conrelid) like '%valid_public_state(public_state)%' from pg_constraint where conrelid='pn_private.presentations'::regclass and conname='public_state_allowlist'),'table CHECK bound to current public validator');
select 'PASS 22 public tool SQL guards';
select pg_temp.ok(pn_private.valid_public_lesson('{"prompt":"P","followup":"F","objective":"O","why":"W","intuitiveOnly":true,"oralReflection":false}'),'catalog lesson accepted');
select pg_temp.ok(not pn_private.valid_public_lesson('{"prompt":"P","followup":"F","objective":"O","why":"W","intuitiveOnly":true,"oralReflection":false,"name":"CANARY"}'),'lesson name rejected');
select pg_temp.ok(not pn_private.valid_public_lesson('{"prompt":"P","followup":"F","objective":"O","why":"W","intuitiveOnly":true,"oralReflection":false,"ink":[1,2,3]}'),'ink rejected');
select pg_temp.ok(pn_private.valid_public_state('{"schemaVersion":1,"mode":"opening","question":1,"taskEpoch":"10000000-0000-4000-8000-000000000001","groups":[],"roles":{"taskId":"10000000-0000-4000-8000-000000000002","pilots":[1,2],"navigators":[3,4]}}'),'opening roles without artificial groups accepted');
select pg_temp.ok(not pn_private.valid_public_state('{"schemaVersion":1,"mode":"station","question":1,"taskEpoch":"10000000-0000-4000-8000-000000000001","groups":[],"roles":{"taskId":"10000000-0000-4000-8000-000000000002","pilots":[1,2],"navigators":[3,4]}}'),'station role membership still required');
select pg_temp.ok(not pn_private.valid_opening_roles('{"taskId":"10000000-0000-4000-8000-000000000002","pilots":[1,2],"navigators":[2,4]}'),'opening duplicate role rejected');
select 'PASS 6 opening/reflection SQL guards';
create temp table balance_fixture(v jsonb);
insert into balance_fixture values('{"kind":"balance","left":{"x":3,"constant":-7},"right":{"x":0,"constant":11}}');
select pg_temp.ok(pn_private.valid_public_tool(v),'balance accepted') from balance_fixture;
select pg_temp.ok(not pn_private.valid_public_tool(v||'{"solution":6}'),'balance answer rejected') from balance_fixture;
select pg_temp.ok(not pn_private.valid_public_tool(v||'{"history":[]}'),'local operation history rejected') from balance_fixture;
select pg_temp.ok(not pn_private.valid_public_tool(jsonb_set(v,'{left,name}','"CANARY"')),'balance nested name rejected') from balance_fixture;
select pg_temp.ok(not pn_private.valid_public_tool(jsonb_set(v,'{right,x}','3')),'nonunique equation rejected') from balance_fixture;
select pg_temp.ok(not pn_private.valid_public_tool(jsonb_set(v,'{right,x}','null')),'null coefficient rejected') from balance_fixture;
select pg_temp.ok(not pn_private.valid_public_tool(jsonb_set(v,'{right,constant}','1001')),'oversized constant rejected') from balance_fixture;
select pg_temp.ok(pn_private.valid_public_state('{"schemaVersion":1,"mode":"station","question":1,"taskEpoch":"10000000-0000-4000-8000-000000000001","groups":[],"pattern":"build"}'::jsonb || jsonb_build_object('tool',v)),'balance accepted in active projection') from balance_fixture;
select 'PASS 8 balance SQL guards';
rollback;
